### ISSUE TITLE
How can I add it on specific page template only?

### ISSUE THREAD

**Issue by vivinblack** [miharekar/mr-meta-box#1]
I want to add some meta options on my custom post type "portfolio" page template only, while other option's on portfolio item adding page only. I can add option on portfolio item adding using
 posttype=> array(portfolio) but how can i add it to portfolio.php template ?

**Comment by miharekar** [comment]
Well that's it, you just have to specify `'postType' => array('portfolio')` and your meta box will appear only there. If you are wondering how to display it on the front end, then you have to call the Wordpress function [get_post_meta](http://codex.wordpress.org/Function_Reference/get_post_meta). The meta `key` is your prefix+name_of_field.

You will probably name your custom page template according to [WP Template Hierarchy](http://codex.wordpress.org/Template_Hierarchy) so `single-portfolio.php`.

Anything else?

**Comment by vivinblack** [comment]
Actually I have added metabox module on  Portfolio posts using 'postType' => array('portfolio') , but now i want to add some meta options on Portfolio template only.  Can you explain how to call this function and where actually i have to add it?

**Comment by miharekar** [comment]
I just did in the previous comment. Please, read it again.

**Comment by vivinblack** [comment]
I got how to get my values in front end for actual use.  But i want to limit my metabox on some specific page template only. Using 'postType' => array('portfolio') or 'postType' => array('slideshow')  adds metbox on each item adding page of portfolio and slideshow. But I want specific metabox module on my specific template like fullscreenslide.php, nivoslider.php or underconstuction.php  and those metabox module available to those pages only.

**Comment by miharekar** [comment]
Ooooh, you mean to limit meta box display to custom post type AND custom page template selected. Sorry, didn't get that at first :smile: 

That's not possible ATM and AFAIK pretty impossible to do since you can change page template on the same page as you display meta box. So on page template change the meta box would have to ajax reload the new meta box. I don't know if that is even possible to do since I would have to catch a page template change on a Wordpress-made input which can change significantly with versions. Not to mention that AJAX content reloading doesn't mix well inside forms.

I would suggest you to build several meta boxes for the same custom post type and name them like you named your page templates. After that you will have to educate whoever will be inputting in those meta boxes which meta box to use for which page template.

I hope that makes sense.

**Comment by vivinblack** [comment]
Sorry I forget to include word "custom post type" in previous comment .And you are right , we need to create metabox for each custom post type. Its tricky and really a new challenge while developing metabox classes. So now I am thinking about to get options using wordpress Option Setting API instead of using metabox for custom post type.
