### ISSUE TITLE
Uncaught TypeError: Cannot call method 'match' of undefined

### ISSUE THREAD

**Issue by Imagica** [miharekar/mr-meta-box#4]
Had an issue with the mr-meta-box.js file when updating an image after I updated WP to v3.6.1. Was getting an error "Uncaught TypeError: Cannot call method 'match' of undefined" on line 102.

I removed the "img" ref from line 102 and 103 to resolve the issue for me:

Original:

```
var imageid = $('img',html).attr('class').match(/wp\-image\-([0-9]+)/);
$this.parent().find('.mr-image').attr('src', $('img', html).attr('src')).show('blind');
```

Changed to:

```
var imageid = $(html).attr('class').match(/wp\-image\-([0-9]+)/);
$this.parent().find('.mr-image').attr('src', $(html).attr('src')).show('blind');
```

The issue was occurring for me when adding a "Slide" background image when using the Hayden theme from ThemeTrust.

**Comment by miharekar** [comment]
Hi!

Thanks for the report, but I'd say that there must be some issue with the theme, cause on my freshly installed WP I cannot reproduce this. I tried uploading, reuploading, deleting, choosing from library and I never get an error.

The way you 'resolved' that just made it worse because now if you'll have an image field it will not show in the meta box when you add it.

Could you send me the theme somehow so I can see what's going on? My email is info [at] mr.si

**Comment by paulwooddesign** [comment]
Looks like wordpress update 3.71 fixed this issue so now the original works again.

**Comment by miharekar** [comment]
Heh, well it doesn't matter - the new one shoud work with both :smile: :+1:
